use_frameworks!

platform :ios, '9.0'

target 'LQAlertViewKit_Example' do
  pod 'LQAlertViewKit', :path => '../'

  target 'LQAlertViewKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
